//create sequence seq_cm_planosaude  increment by 1 minvalue 0 nocache;

CREATE TABLE CM_PLANOSAUDE ( 
       LOGIN            VARCHAR2(20) NOT NULL,
       IDPESSOA         NUMBER(8) NOT NULL,
       PLANOSAUDE       VARCHAR2(50) NOT NULL
);

ALTER TABLE CM_PLANOSAUDE ADD CONSTRAINT PK_CM_PLANOSAUDE PRIMARY KEY(LOGIN);
// ALTER TABLE CM_PLANOSAUDE ADD CONSTRAINT FK_CM_PLANOSAUDE1 FOREIGN KEY(IDPESSOA) REFERENCES CM_PESSOA;
ALTER TABLE CM_PLANOSAUDE ADD CONSTRAINT FK_CM_PLANOSAUDE2 FOREIGN KEY(LOGIN) REFERENCES CM_USUARIO(LOGIN);

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','BRADESCO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','CROE');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','GOLDEN CROSS');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','PLANSFER');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','PLASC');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','UNIMED');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1) VALUES (SEQ_CM_TABELAGERAL.NEXTVAL,'PLANOSAUDE','AME');

