INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2,ITEM3) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_CATEGORIAEQUIPE','1', 'COORDENACAO', '');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2,ITEM3) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_CATEGORIAEQUIPE','2', '', 'SUB-COORDENACAO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2,ITEM3) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_CATEGORIAEQUIPE','3', '', 'EQUIPE DE TRABALHO');

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','1', 'AMBIENTE FISICO DO TRABALHO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','2', 'EQUIPAMENTOS DE TRABALHO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','3', 'RECURSOS HUMANOS');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','4', 'RELACIONAMENTO INTERPESSOAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','5', 'CONDICOES DE SAUDE');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','6', 'CAPACITACAO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FATORDIFICULT','7', 'OUTRO');

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FINALIDADECONTAGEM','1', 'APOSENTADORIA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FINALIDADECONTAGEM','2', 'LICENCA-PREMIO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FINALIDADECONTAGEM','3', 'ADICIONAL POR TEMPO DE SERVICO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_FINALIDADECONTAGEM','4', 'PROGRESSAO FUNCIONAL');

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTMEMBRO','1','HABILITADO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTMEMBRO','2','NAO HABILITADO');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTPROADES','1','ATINGIU');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTPROADES','2','NAO ATINGIU');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTREUNIAO','1','ALCANCADOS');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTREUNIAO','2','PARCIALMENTE ALCANCADOS');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_RESULTREUNIAO','3','NAO ALCANCADOS');

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_STATUSPROADES','1','EM ANDAMENTO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_STATUSPROADES','2','ENCERRADA');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOADICIONAL','2','PERICULOSIDADE');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOADICIONAL','3','RAIO X');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOADICIONAL','1','INSALUBRIDADE');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOCESSAO','1','REQUISICAO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOCESSAO','2','CESSAO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOCESSAO','3','MANDATO CLASSISTA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOCESSAO','4','LOTACAO PROVISORIA');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPODEPENDENCIA','SF','SALARIO-FAMILIA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPODEPENDENCIA','PA','PENSAO ESPECIAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPODEPENDENCIA','PE','PENSAO ESPECIAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPODEPENDENCIA','IR','IMPOSTO DE RENDA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPODEPENDENCIA','AP','ASSISTENCIA PRE-ESCOLAR');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','1','SOCIEDADE DE ECONOMIA MISTA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','2','MUNICIPAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','3','ESTADUAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','4','FEDERAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','5','PRIVADO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOINSTITUICAO','6','MIGRACAO');

INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOLICENCA','INTEGRAL','INTEGRAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOLICENCA','PARCIAL','PARCIAL');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOONUS','1','ONUS INTEGRAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOONUS','2','ONUS PARCIAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOONUS','3','SEM ONUS');
--
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','DOC_IMF','DOCENTE DE ENSINO INFANTIL, MEDIO E FUNDAMENTAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','DOC_MAG','DOCENTE MAGISTERIO');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','FAR','FORCAS ARMADAS');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','SDF','SERVICO PUBLICO DISTRITO FEDERAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','SPE','SERVICO PUBLICO ESTADUAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','SPF','SERVICO PUBLICO FEDERAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','SPM','SERVICO PUBLICO MUNICIPAL');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','SPR','INICIATIVA PRIVADA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','TGU','TIRO DE GUERRA');
INSERT INTO CM_TABELAGERAL (IDTABELAGERAL,TABELA,ITEM1,ITEM2) VALUES ((SELECT NEXTVAL('SEQ_CM_TABELAGERAL')),'RH_TIPOTEMPO','AJD','AVERBACAO JUDICIAL');

